[package]
name = "wa-demo"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
watt = "0.4"

[features]
default = []
proc-macro-server = ["watt/proc-macro-server"]
nightly = ["watt/nightly"]