name: CI

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [beta, stable, 1.42.0]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          target: wasm32-unknown-unknown
      - run: cargo build --manifest-path demo/impl/Cargo.toml --release --target wasm32-unknown-unknown
      - run: cargo run --manifest-path demo/caller/Cargo.toml
      - run: cargo test --manifest-path runtime/tests/Cargo.toml
      - run: cargo test --manifest-path proc-macro/Cargo.toml
      - run: cargo check --features proc-macro-server
      - run: WATT_JIT=1 cargo check
  
  nightly:
    name: Rust nightly
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
      - run: cargo build --manifest-path demo/impl/Cargo.toml --release --target wasm32-unknown-unknown
      - run: cargo build --manifest-path demo/impl-proc-macro-server/Cargo.toml --release --target wasm32-unknown-unknown
      - run: cargo run --manifest-path demo/caller/Cargo.toml
      - run: cargo run --manifest-path demo/caller/Cargo.toml --features proc-macro-server
      - run: cargo run --manifest-path demo/caller/Cargo.toml --features nightly
      - run: cargo test --manifest-path runtime/tests/Cargo.toml
      - run: cargo test --manifest-path proc-macro/Cargo.toml
      - run: WATT_JIT=1 cargo check
      - run: WATT_JIT=1 cargo check --features proc-macro-server
      - run: WATT_JIT=1 cargo check --features nightly

  msrv:
    name: Rust 1.35.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.35.0
      - run: cargo check
